### ISSUE TITLE
subtract with overflow in `BrotliDecompress`

### ISSUE THREAD

**Issue by catenacyber** [dropbox/rust-brotli-decompressor#24]
Hi @danielrh 

Here is a reproducer for this case found by oss-fuzz on suricata : https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55711&q=label%3AProj-suricata

```Cargo.toml
[package]
name = "brotlol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brotli = "~3.3.0"
```

```src/main.rs
use std::io;

fn main() {
    let failing = vec![17, 27, 17, 17, 17, 17, 149, 149, 37, 208, 17, 17, 149, 149, 236, 234, 0, 0, 0, 8, 0, 0, 32, 44, 32, 44, 255, 255, 255, 255, 61, 4, 103, 122, 0, 0, 247, 115, 105, 114, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 252, 0, 0, 32, 0, 0, 0, 0, 33, 225, 252];
    match brotli::BrotliDecompress(&mut failing.as_slice(), &mut io::stdout()) {
        Ok(_) => {
            println!("Ok, world!");
        }
        Err(_) => {
            println!("Error, world!")
        }
    }
}
```

Build it with `RUSTFLAGS=-Cdebug-assertions=yes cargo build`

And I run it with `RUST_BACKTRACE=1 ./target/x86_64-apple-darwin/debug/brotlol`, I get
```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/decode.rs:2320:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0442fbabe24ec43636a80ad1f40a0ad92a2e38df/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/0442fbabe24ec43636a80ad1f40a0ad92a2e38df/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/0442fbabe24ec43636a80ad1f40a0ad92a2e38df/library/core/src/panicking.rs:114:5
   3: brotli_decompressor::decode::ProcessCommandsInternal
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/decode.rs:2320:15
   4: brotli_decompressor::decode::ProcessCommands
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/decode.rs:2616:3
   5: brotli_decompressor::decode::BrotliDecompressStream
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/decode.rs:3151:20
   6: brotli_decompressor::BrotliDecompressCustomIoCustomDict
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/lib.rs:265:14
   7: brotli_decompressor::BrotliDecompressCustomIo
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/lib.rs:196:3
   8: brotli_decompressor::BrotliDecompressCustomAlloc
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/lib.rs:169:3
   9: brotli_decompressor::BrotliDecompress
             at /Users/catena/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-decompressor-2.3.4/src/lib.rs:86:3
  10: brotlol::main
             at ./src/main.rs:5:11
  11: core::ops::function::FnOnce::call_once
             at /rustc/0442fbabe24ec43636a80ad1f40a0ad92a2e38df/library/core/src/ops/function.rs:250:5
```

What do you think of this ?

**Comment by catenacyber** [comment]
C brotli fails `ProcessCommands` fails early and `SafeProcessCommands` does not get this underflow...

**Comment by catenacyber** [comment]
Thanks @danielrh fixed by https://github.com/dropbox/rust-brotli-decompressor/commit/0045b6e18a91b12937ffc45a7a4f934ffeab7d2e

**Comment by catenacyber** [comment]
Well, I can stil reproduce it with brotli-decompressor-2.3.4 and brotli v3.3.4

I did not know why I closed this...
